# Swiftlint configuration file.
# Part of Aurora Editor.
# Please do not remove optional rules, feel free to add some if needed.

# Disabled rule, reason.
disabled_rules:
  - todo # New project, we have a lot of // TODO:
  - static_over_final_class # We need to fix this (later)
  - non_optional_string_data_conversion # We need to fix this (later)

# paths to ignore during linting.
excluded:
  - AuroraEditorModules/.build # Where Swift Package Manager checks out dependency sources
  - AuroraEditorCli/Package.swift # Package.swift should not be linted
  - Tools # Tools should not be linted
  - "AuroraEditor/Base/Version Control" # This will be removed soon, @nanashili remove when done.

# Exclude triggering type names.
type_name:
  excluded:
    - ID

# Exclude triggering identifier names.
identifier_name:
  excluded:
    - id
    - vc
    - up
    - to
    # (short) File extensions:
    - c
    - m
    - h
    - js
    - md
    - py
    - go
    - ts
    - txt
    - sh
    - pf
    - r
    - q
    - tp
    - xl
    - hy
    - d
    - cs

# cyclomatic_complexity (ignore case)
cyclomatic_complexity:
  ignores_case_statements: true

# Opt in rules, we want it more stricter.
opt_in_rules:
  - file_header # All files should have a same header.
  - empty_count # Use .isEmpty instead of .count == 0
  - closure_spacing # Closure should have a space before and after the braces
  - contains_over_first_not_nil # Use .contains instead of .first(where:)
  - missing_docs # Required documentation for public functions
  - modifier_order # Modifier order should be consistent
  - convenience_type # Use convenience type instead of type with default values
  - pattern_matching_keywords # Use pattern matching keywords instead of 'is' and 'as'
  - identical_operands # Identical operands should be avoided
  - empty_string # Use .isEmpty instead of .count == 0
  - multiline_parameters # Multiline parameters should be indented the same as the line they are on
  - closure_end_indentation # Closure end should be indented the same as the line the closure starts
  - operator_usage_whitespace # Operator should be surrounded by whitespace
  - closure_parameter_position # Closure parameters should be on the same line as the opening brace
  - collection_alignment  # Collection should have the same alignment
  - last_where # Use last(where:) instead of filter().last
  - unused_optional_binding # Unused optional binding should be avoided
  - toggle_bool # use .toggle() instead of !variable
  - explicit_init # .init is not needed
  - fallthrough # fallthrough is not allowed
  - no_fallthrough_only # fallthrough should not be the only statement in a case body
  - comment_spacing # Comments should be followed by a space
  - orphaned_doc_comment # Orphaned doc comment should be avoided
  - local_doc_comment # Local doc comment should be avoided
  - accessibility_label_for_image # Accessibility label for image should be set
  - accessibility_trait_for_button # Accessibility trait for button should be set

analyzer_rules:
  - unused_import # Detect unused imports

# Custom configuration for nesting, this needs to be removed at some point.
nesting:
  type_level:
    warning: 2 # warning if you nest 2 level deep instead of 1
    error: 3 # error if you nest 3 level deep instead of 1

# Custom rules
custom_rules:
  # Prefer spaces over tabs.
  spaces_over_tabs:
    included: ".*\\.swift"
    name: "Spaces over Tabs"
    regex: "\t"
    message: "Prefer spaces for indents over tabs. See Xcode setting: 'Text Editing' -> 'Indentation'"
    severity: warning

  # @Something needs a new line
  at_attributes_newlining:
    name: "Significant attributes"
    message: "Significant @attributes should be on an extra line"
    included: ".*.swift"
    regex: '(@objc\([^\)]+\)|@nonobjc|@discardableResult|@propertyWrapper|@UIApplicationMain|@dynamicMemberLookup|@_cdecl\([^\)]+\))[^\n]'
    severity: error

  # forbid multiple empty lines
  multiple_empty_lines:
    included: ".*.swift"
    name: "Multiple Empty Lines"
    regex: '((?:\s*\n){3,})'
    message: "There are too many line breaks"
    severity: error

  # one space after a comma
  comma_space_rule:
    regex: ",[ ]{2,}"
    message: "Expected only one space after ',"
    severity: error

  # Disable usage of // swiftlint:disable (rulename)
  swiftlint_file_disabling:
    included: ".*.swift"
    name: "SwiftLint File Disabling"
    regex: "swiftlint:disable\\s"
    match_kinds: comment
    message: "Use swiftlint:disable:next or swiftlint:disable:this"
    severity: error

  # Don't use print
  disallow_print:
    included: ".*.swift"
    name: "No print"
    regex: "print(.*)"
    message: "Please do not use print(), use `Log.info()`."
    severity: warning

  # Disable Xcode placeholders like <#Description#>
  no_placeholders:
    included: ".*.swift"
    name: "No Placeholders"
    regex: "\\<\\#([a-zA-Z]+)\\#\\>"
    message: "Please do not use Xcode's placeholders."
    severity: warning

  # Don't use #Preview macro
  no_preview_macro:
    included: ".*.swift"
    name: "No Preview Macro"
    regex: "\\#Preview"
    message: "Do not use preview macro."
    severity: warning

  # Don't use /** style doc comments
  no_double_star_doc_comments:
    included: ".*.swift"
    name: "No Double Star Doc Comments"
    regex: "/\\*\\*\n"
    message: "Do not use /** style doc comments."
    severity: warning

  # Dont use @param in doc comments
  no_param_in_doc_comments:
    included: ".*.swift"
    name: "No @param in Doc Comments"
    regex: "@param"
    message: "Do not use @param in doc comments."
    severity: warning

file_header:
  required_pattern: |
                  \/\/
                  \/\/  .*?\.swift
                  \/\/  Aurora Editor(| UITests| Tests| Updater)
                  \/\/
                  \/\/  Created by .*? on .*?\.
                  \/\/  Copyright © \d{4} Aurora Company. All rights reserved.
                  \/\/
