name: Clean xcodeproj
run-name: "Remove DEVELOPMENT_TEAM from xcode project"

on:
  pull_request:
    branches:
      - development

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  clean:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'AuroraEditor'
    env:
      xcodeproj: "Aurora Editor.xcodeproj/project.pbxproj"
    steps:
      - uses: actions/checkout@v2

      - name: Check if we need to empty DEVELOPMENT_TEAM.
        id: needs-removal
        run: |
          rec="$( grep -cE "DEVELOPMENT_TEAM = [[:alnum:]]{1,20};" "$xcodeproj" || true )"
          if [[ "$rec" > 0 ]] ; then
            echo "needs-removal=1" >> "$GITHUB_OUTPUT"
          else
            echo "needs-removal=0" >> "$GITHUB_OUTPUT"
          fi

      - name: Rewrite DEVELOPMENT_TEAM
        if: ${{ steps.needs-removal.outputs.needs-removal == 1 }}
        run: |
          cp "$xcodeproj" "temp"
          # Sed to the same file causes issues, so we use a temp file.
          sed 's/DEVELOPMENT_TEAM = .*;/DEVELOPMENT_TEAM = "";/g' "temp" > "$xcodeproj"
          rm "temp"

          if [ ! -s "$xcodeproj" ] ; then 
            echo "::error file=$xcodeproj,line=1::Xcodeproject file is empty"
            exit 1
          fi

      - name: Setup github environment
        if: ${{ steps.needs-removal.outputs.needs-removal == 1 }}
        run: |
          git config --global user.name 'aurora-editor-bot'
          git config --global user.email 'aurora-editor-bot@users.noreply.github.com'

      - name: push to Github
        if: ${{ steps.needs-removal.outputs.needs-removal == 1 }}
        run: |
          echo "Current branch: $GITHUB_HEAD_REF"
          git add . --all
          git commit -m "Removed development team"
          git push origin HEAD:$GITHUB_HEAD_REF --force
