name: Run Aurora Editor Tests

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: self-hosted
    timeout-minutes: 10 # If an action exceeds 10 mins, it probably isn't ever going to complete.
    steps:
      - name: Clean up
        if: always()
        run: |
          echo "Cleaning up derived data"
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          echo "Clean up complete"

      - uses: actions/checkout@v3

      - name: Runner environment
        run: |
          echo "MacOS Version"
          sw_vers
          echo "Toolchain version"
          swift -version
          echo "SwiftLint (version)"
          swiftlint version

      - name: Aurora Editor (Tests)
        run: |
          set -o pipefail
          xcodebuild -resolvePackageDependencies
          xcodebuild -quiet \
          -workspace "Aurora Editor.xcworkspace" \
          -scheme "Aurora Editor (Tests)" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          test

