name: Clean & Sort Xcode Project
run-name: "Remove DEVELOPMENT_TEAM from xcode project"

on:
  pull_request:
    branches:
      - development

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  clean:
    runs-on: macos-latest
    if: github.repository_owner == 'AuroraEditor'
    env:
      xcodeproj: "Aurora Editor.xcodeproj/project.pbxproj"
    steps:
      - uses: actions/checkout@v3

      - name: Check if we need to empty DEVELOPMENT_TEAM.
        id: needs-removal
        run: |
          rec="$( grep -cE "DEVELOPMENT_TEAM = [[:alnum:]]{1,20};" "$xcodeproj" || true )"
          if [[ "$rec" > 0 ]] ; then
            echo "needs-removal=1" >> "$GITHUB_OUTPUT"
          else
            echo "needs-removal=0" >> "$GITHUB_OUTPUT"
          fi

      - name: Rewrite DEVELOPMENT_TEAM
        if: ${{ steps.needs-removal.outputs.needs-removal == 1 }}
        run: |
          cp "$xcodeproj" "temp"
          # Sed to the same file causes issues, so we use a temp file.
          sed 's/DEVELOPMENT_TEAM = .*;/DEVELOPMENT_TEAM = "";/g' "temp" > "$xcodeproj"
          rm "temp"

          if [ ! -s "$xcodeproj" ] ; then 
            echo "::error file=$xcodeproj,line=1::Xcodeproject file is empty"
            exit 1
          fi

      - name: Make Sort Xcode Project Script Executable
        run: |
          cd "$(pwd)/Tools"
          chmod +x sort-Xcode-project-file.pl

      - name: Sort Xcode Project
        run: |
          cd "$(pwd)/Tools"
          ./sort-Xcode-project-file.pl --warnings "../Aurora Editor.xcodeproj"

      - name: Setup GitHub Environment
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Push to GitHub
        env:
          PAT_TOKEN: ${{ secrets.PAT }}
        run: |
          echo "Current branch: $GITHUB_HEAD_REF"
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git
          if [ -n "$(git status --porcelain)" ]; then
            git add . --all
            git commit -m "Cleaned Up Xcode Project File"
            git push origin HEAD:$GITHUB_HEAD_REF --force
          else
            echo "No changes to commit"
          fi
